### ISSUE TITLE
Componentes

### ISSUE THREAD

**Issue by natanprog** [alberteije/T2TiERP-2-Lazarus#1]
**ACBr** https://sourceforge.net/p/acbr/code/HEAD/tree/trunk2
**Brook** https://github.com/risoflora/brookfreepascal
**FortesReport** https://github.com/fortesinformatica/fortesreport-ce
**LabeledControls** https://github.com/alberteije/SAT-CF-e-Lazarus/blob/master/LabeledControls.rar (**Sugestão:** Adicionar esse componente **LabeledControls** no repositório)
**LJGridUtils** https://github.com/risoflora/brookfreepascal/tree/master/plugins/ljgridutils
**PowerPDF** https://sourceforge.net/p/lazarus-ccr/svn/HEAD/tree/components/powerpdf
**Rx library** https://sourceforge.net/p/lazarus-ccr/svn/HEAD/tree/components/rx/trunk
**SpkToolbar** https://sourceforge.net/p/lazarus-ccr/svn/HEAD/tree/components/spktoolbar
**ZeosLib** https://sourceforge.net/p/zeoslib/code-0/HEAD/tree/branches/7.2-patches
Nativo da IDE
**LazActiveX** components\activex\LazActiveX.lpk
**LazReport** components\lazreport\source\lazreport.lpk
**LazReport PDF exporter** components\lazreport\source\addons\pdfexport\lazreportpdfexport.lpk

Não encontrei essa informação no repositório, estou compartilhando aqui os componentes necessários para compilar os fontes (Links das versões mais atuais dos componentes, pois não sei quais foram as versões utilizadas)

**Comment by alberteije** [comment]
Natan,

Obrigado!

Abraços
Albert Eije

**Comment by wagnerlcg** [comment]
Natan, tudo bem?
Ao compilar no meu ambiente, não encontra a unit ZDataSet.
Vc teria esta unit?
Grato.
Wagner

**Comment by Brizolla10** [comment]
ao compilar o projeto da erro nesse pacote LabeledControls [curredit] alguem sabe como resolver

**Comment by gheysiell** [comment]
A solução para Lazarus IDE sobre o pacote curredit é instalar o pacote Rx no gerenciador de pacotes online e substituir curredit e tooledit por rxcurredit e rxtooledit respectivamente.
